# Generated by Django 3.1.6 on 2022-08-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('provider_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('provider_name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('send_code', models.CharField(max_length=30)),
                ('receive_code', models.CharField(max_length=30)),
                ('status_user', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ip_addresses', models.CharField(max_length=50)),
                ('name_pointofsale', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('validation_code', models.CharField(max_length=6, unique=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_receiver', to='api.users')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sender', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status_account', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='api.users')),
            ],
        ),
    ]
