# Generated by Django 3.1.6 on 2022-08-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='users',
            name='contact',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
