# Generated by Django 3.1.6 on 2022-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220817_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='En attente', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='status_user',
            field=models.CharField(default='client', max_length=50),
        ),
    ]
