# Generated by Django 3.1.6 on 2022-08-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220818_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='provider',
            field=models.ForeignKey(default='Instapay', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.providers'),
        ),
    ]
