# Generated by Django 3.1.6 on 2022-08-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accounts_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='providers',
            name='provider_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
