# Generated by Django 3.1.6 on 2022-08-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220820_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='validation_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
