# Generated by Django 3.1.6 on 2022-08-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220823_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.FloatField(default=100000),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_owner', to='api.users'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='provider',
            field=models.ForeignKey(default='Instapay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_provider', to='api.providers'),
        ),
    ]
