# Generated by Django 3.1.6 on 2022-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220826_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.FloatField(default=1000000),
        ),
    ]
